spring:
  datasource:
    url: jdbc:h2:mem:energy;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update

server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: framework
